In [1]:
import numpy as np

In [2]:
def no_zeros(arrayInput):
    ## TODO: This function should return True if 
    ## numpy array arrayInput does not contain any zero
    ## and will return False otherwise.
    ## Implement this function using ONLY numpy methods
    ## Sample input: [1,2,3,4,5,6,0] Sample Output: False
    return False


    # Check if any element in the array is equal to zero
    return not np.any(arrayInput == 0)

# Example
sample_input = np.array([9, 8, 7, 6, 5, 4, 0])
result = no_zeros(sample_input)
print(result)

False


In [3]:
def linearly_distributed(n, min, max):
    ## TODO: This function should return a numpy array of 
    ## length n with equally spaced elements from 
    ## min (inclusive) to max (exclusive)
    ## Implement this function using ONLY numpy methods
    ## Sample input: (4,0,100) sample output [0,33,66, 99]
    return np.array({})


import numpy as np

def linearly_distributed(n, min_val, max_val):
    # Use numpy's linspace to generate equally spaced values
    return np.linspace(min_val, max_val, n, endpoint=False, dtype=int)

# Example
result = linearly_distributed(6, 0, 600)
print(result)


[  0 100 200 300 400 500]


In [4]:
def two_dimensions(n):
    ## TODO: This function should create a 2d Array of shape n*n
    ## Where the borders of the array are ones
    ## all other elements are zero
    ## Implement this function using ONLY numpy methods
    ## Sample input 3
    ## sample output [[1,1,1],[1,0,1],[1,1,1]]
    return np.array({})


def two_dimensions(n):
    #  a 2D array with ones on the borders and zeros in the interior
    arr = np.zeros((n, n), dtype=int)
    arr[0, :] = 1  # set first row to ones
    arr[-1, :] = 1  # set last row to ones
    arr[:, 0] = 1  #  set first col to ones
    arr[:, -1] = 1  # set last col to ones

    return arr
result = two_dimensions(3)
print(result)

    

[[1 1 1]
 [1 0 1]
 [1 1 1]]


In [5]:
def create_array(n,min,max):
    ## TODO: This function should return a numpy array of 
    ## length n with random elements from 
    ## min (inclusive) to max (exclusive)
    ## Implement this function using ONLY numpy methods 
    ## USE np.random.rand for generating the numbers 
    ## Sample Input (10,0,10) sample output(0,2,2,3,1,5,9,7,8,3)
    return np.array({})


def create_array(n, min_val, max_val):
    # generate random values between 0 and 1 by using np.random.rand
    random_values = np.random.rand(n)

    # Scale and shift the values to the desired range [min, max)
    result = (max_val - min_val) * random_values + min_val

    # Round  values to integers
    result = result.astype(int)


    return result

result = create_array(5, 0, 5)
print(result)

[2 3 1 0 1]


In [6]:
def random_generation(n,min,max):
    ## TODO: Write a function that takes as an input
    ## Dimension of 2d Array n, min and max
    ## Generate an n*n array with random numbers between
    ## min and max inclusive
    ## Such that no element is duplicated
    ## return numpy array
    ## Implement this function using ONLY numpy methods
    ## Sample Input: random_generation(3,0,12) --> [[4,2,6],[1,5,11],[10, 3,9]]
    return np.array({})

#Solution

def random_generation(n, min_val, max_val):
    # Calculate total number of elements in the array
    total_elements = n * n

    # unique random numbers between min and max (inclusive)
    unique_numbers = np.random.choice(np.arange(min_val, max_val + 1), total_elements, replace=False)

    # Reshape  1D array into a 2D array of size n*n
    result = unique_numbers.reshape((n, n))

    return result

# Example usage:
result = random_generation(4,0,16)

print(result)

[[14  4  6 11]
 [ 1 10  9  5]
 [ 2  3 16 12]
 [ 7  0 15  8]]
